### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by QAbot-zh** [ubi-agni/STP#1]
hello, I am trying to compile the cpp folder, but I get error info as follow:

> mkdir o.
generating dependencies for file complex.cc
generating dependencies for file polynomial.cc
generating dependencies for file tools.cc
generating dependencies for file stp1.cc
generating dependencies for file stp3.cc
generating dependencies for file stp7.cc
generating dependencies for file stp7Formulars.cc
generating dependencies for file STP.cc
generating dependencies for file MultiSTP.cc
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c complex.cc -o o./complex.o
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c polynomial.cc -o o./polynomial.o
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c tools.cc -o o./tools.o
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c stp1.cc -o o./stp1.o
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c stp3.cc -o o./stp3.o
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c stp7.cc -o o./stp7.o
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c stp7Formulars.cc -o o./stp7Formulars.o
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c STP.cc -o o./STP.o
g++ -O4 -march=native -mtune=native -I/vol/nirobots/include -I/vol/xcf/include -DUSE_LOG4CXX -fPIC -c MultiSTP.cc -o o./MultiSTP.o
MultiSTP.cc:9:21: fatal error: Logger.hh: No such file or directory
compilation terminated.
makefile:74: recipe for target 'o./MultiSTP.o' failed
make: *** [o./MultiSTP.o] Error 1

It seems the project is missing some file. Could you help me?

**Comment by guihomework** [comment]
you are right the file `Logger.hh` is part of a non-shared wrapper ni-logger around log4cpp.
@rhaschke , can one simply disable the logging removing USE_LOG4CXX

**Comment by rhaschke** [comment]
As @guihomework correctly stated, `Logger.hh` is part of an external repo. I will send you a tarball of it via email.
The compiler flag `USE_LOG4CXX` just refers to using `log4cpp` or not in our Logger lib. Removing it, will not resolve your issue.

**Comment by rhaschke** [comment]
I couldn't find your email. Please find the repo in [this gist](https://gist.github.com/rhaschke/4d4e266831ce6834206daf46ad1d9ee0).

**Comment by QAbot-zh** [comment]
Thank you for your apply. I try to disable LOG4CXX， and the logger problem seems to be solved. But I get the new problem:
> progaux_stp.cc:4:17: fatal error: nst.h: No such file or directory
compilation terminated.
makefile:74: recipe for target 'o./progaux_stp.o' failed
make: *** [o./progaux_stp.o] Error 1

By the way, my email address is zhongxianyou@tongji.edu.cn , if you need.

**Comment by rhaschke** [comment]
> I try to disable LOG4CXX, and the logger problem seems to be solved.

Good.

> But I get the new problem: `progaux_stp.cc:4:17: fatal error: nst.h`

Skip building `stp.so`, changing this line
https://github.com/ubi-agni/STP/blob/dd0204af3d5d34a65fc972082caef1a1a9286fdb/cpp/makefile#L8

to:
```diff
- all: depend libSTP.so stp.so
+ all: depend libSTP.so
```

**Comment by rhaschke** [comment]
By the way, if you are interested in a smooth motion generator, better consider https://github.com/pantor/ruckig than this old code here.

**Comment by QAbot-zh** [comment]
Thank you soooo much! Your suggestion and recommendation help a lot!
